export const occupationOptions = [
  { value: "ইমাম" },
  { value: "মাদ্রাসা শিক্ষক" },
  { value: "শিক্ষক" },
  { value: "ডাক্তার" },
  { value: "ইঞ্জিনিয়ার" },
  { value: "ব্যবসায়ী" },
  { value: "সরকারী চাকুরী" },
  { value: "বেসরকারী চাকুরী" },
  { value: "ফ্রিল্যান্সার" },
  { value: "শিক্ষার্থী" },
  { value: "প্রবাসী" },
  { value: "অন্যান্য" },
  { value: "পেশা নেই" },
];
