#dangerous-clean-slate: true

name: 🚀 Deploy PNC-Nikah-Front-End website on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    env:
      VITE_REACT_APP_authDomain: ${{ secrets.REACT_APP_AUTHDOMAIN }}
      VITE_REACT_APP_apiKey: ${{ secrets.REACT_APP_APIKEY }}
      VITE_REACT_APP_projectId: ${{ secrets.REACT_APP_PROJECTID }}
      VITE_REACT_APP_storageBucket: ${{ secrets.REACT_APP_STORAGEBUCKET }}
      VITE_REACT_APP_messagingSenderId: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
      VITE_REACT_APP_appId: ${{ secrets.REACT_APP_APPID }}
      VITE_REACT_APP_NODE_ENV: ${{secrets.REACT_APP_NODE_ENV}}
    steps:
      - name: environment variable
        run: echo Hello world $REACT_APP_IMGBB_KEY

      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: 🔨 Build Project
        run: |
          npm install --legacy-peer-deps
          CI=false npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{secrets.FTP_USERNAME}}
          # dangerous-clean-slate: true
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          local-dir: ./dist/
